services:
   the_game.game_master:
       class: GameBundle\Service\GameMaster
       arguments: ["@the_game.game_world"]

   the_game.game_world:
       class: GameBundle\Service\GameWorld
       # arguments: ["@service_id", "plain_value", "%parameter%"]
